version: '3'

services:
  db:
    container_name: 'db'
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'appdb'
       MYSQL_PASSWORD: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - 'db:/var/lib/mysql'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    container_name: 'redis'
    image: 'redis:5'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001 
    volumes:
      - '.:/base'
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis

volumes:
  redisdata:
  db:
  .: