# Generated by Django 3.1.3 on 2020-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default-user-image.png', null=True, upload_to=''),
        ),
    ]
