# Generated by Django 3.1.5 on 2021-01-21 13:21

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    City = apps.get_model("specialistservice", "City")

    City.objects.using(db_alias).bulk_create(
        [City(name="Минск"),
         City(name="Брест")]
    )


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    City = apps.get_model("specialistservice", "City")

    City.objects.using(db_alias).filter(name='Минск').delete()
    City.objects.using(db_alias).filter(name='Брест').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0002_add_groups'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)

    ]
