# Generated by Django 3.1.5 on 2021-01-21 13:21

from django.db import migrations

def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Specialty = apps.get_model("specialistservice", "Specialty")

    Specialty.objects.using(db_alias).bulk_create(
        [Specialty(name="Сантехник"),
         Specialty(name="Программист"),
         Specialty(name="Бухгалтер")]
    )

def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Specialty = apps.get_model("specialistservice", "Specialty")

    Specialty.objects.using(db_alias).filter(name = 'Сантехник').delete()
    Specialty.objects.using(db_alias).filter(name = 'Программист').delete()
    Specialty.objects.using(db_alias).filter(name = 'Бухгалтер').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0003_add_cities'),
    ]

    operations = [    
        migrations.RunPython(forwards_func, reverse_func)
    ]