# Generated by Django 3.1.3 on 2020-12-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0003_auto_20201209_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'permissions': (('can_update_specialist_info', 'Set new specialist info'), ('can_become_specialist', 'Can become specialist'))},
        ),
    ]
