# Generated by Django 3.1.3 on 2020-12-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0004_auto_20201209_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='works_at_home',
            new_name='departure_to_client',
        ),
    ]
