# Generated by Django 3.1.3 on 2020-12-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0005_auto_20201210_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='departure_to_client',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialistservice.specialty'),
        ),
    ]
