# Generated by Django 3.1.3 on 2020-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialistservice', '0006_auto_20201210_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='about',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
